[project]
name = "bbd-language-extension"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygls>=2.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
